### ISSUE TITLE
aegean crashing with error: pickle data was truncated

### ISSUE THREAD

**Issue by haltiamreptar** [PaulHancock/Aegean#108]
I am trying to run aegean over the full 10 tile EMU pilot mosaic for comparison with outer source finders, and to also verify if our catalogue merging procedures are correct. When I run the tool it crashes with the error:
19908:pprocess:ERROR pickle data was truncated

This occurs under python 3.6 and 3.7 installed via apt on Ubuntu 18.04.3 LTS. The machine I am running it on has 16 cores and 48Gb of memory.

The full run log is:
`Sat  4 Jan 16:48:01 AEDT 2020
19804:aegean:INFO This is Aegean 2.1.0-(2019-10-06)
19804:aegean:INFO Found 16 cores
19804:aegean:INFO Using 16 cores
19804:aegean:INFO Found background ten-tile.image.emu-pilot.i.taylor.0_bkg.fits
19804:aegean:INFO Found noise ten-tile.image.emu-pilot.i.taylor.0_rms.fits
19804:aegean:INFO Finding sources.
WARNING: FITSFixedWarning: PC01_01 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC01_01 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC02_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC02_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC03_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC03_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC04_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC04_01 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC01_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC01_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC02_02 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC02_02 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC03_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC03_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC04_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC04_02 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC01_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC01_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC02_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC02_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC03_03 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC03_03 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC04_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC04_03 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC01_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC01_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC02_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC02_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC03_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC03_04 = 0.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: PC04_04 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: PC04_04 = 1.000000000000E+00 
indices in parameterized keywords must not have leading zeroes.
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   116.658800 from OBSGEO-[XYZ].
Set OBSGEO-B to   -26.704100 from OBSGEO-[XYZ].
Set OBSGEO-H to      121.995 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
19804:logger:WARNING FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   116.658800 from OBSGEO-[XYZ].
Set OBSGEO-B to   -26.704100 from OBSGEO-[XYZ].
Set OBSGEO-H to      121.995 from OBSGEO-[XYZ]'.
19804:source_finder:INFO Loading background data from file ten-tile.image.emu-pilot.i.taylor.0_bkg.fits
19804:source_finder:INFO Loading rms data from file ten-tile.image.emu-pilot.i.taylor.0_rms.fits
19804:source_finder:INFO beam = 14.78'' x 11.05'' at -59.00deg
19804:source_finder:INFO seedclip=5
19804:source_finder:INFO floodclip=4
19908:pprocess:ERROR pickle data was truncated
Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 1205, in start
    callable(channel, *args, **kw)
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 957, in __call__
    t = channel.receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 125, in _receive
    obj = pickle.load(self.read_pipe)
_pickle.UnpicklingError: pickle data was truncated
19829:pprocess:ERROR pickle data was truncated
Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 1205, in start
    callable(channel, *args, **kw)
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 957, in __call__
    t = channel.receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 125, in _receive
    obj = pickle.load(self.read_pipe)
_pickle.UnpicklingError: pickle data was truncated
19828:pprocess:ERROR pickle data was truncated
Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 1205, in start
    callable(channel, *args, **kw)
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 957, in __call__
    t = channel.receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/home/evan/.local/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 125, in _receive
    obj = pickle.load(self.read_pipe)
_pickle.UnpicklingError: pickle data was truncated
19804:aegean:INFO found 442304 sources total
Sun  5 Jan 00:40:16 AEDT 2020`

**Comment by ajstewart** [comment]
I also have the same error, it's usually when a connection has been terminated - e.g. I leave a process running in a screen and logout from the remote server.

If I log back in, re-create the screen and start the process again it then complete successfully.

Looks like something to do with pprocess - is there any reason why pprocess is needed over using multiprocessing?

```
133969:aegean:INFO This is Aegean 2.1.1-(2020-01-16)
133969:aegean:INFO Using 12 cores
133969:aegean:INFO Finding sources.
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   116.658800 from OBSGEO-[XYZ].
Set OBSGEO-B to   -26.704100 from OBSGEO-[XYZ].
Set OBSGEO-H to      121.995 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
133969:logger:WARNING FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   116.658800 from OBSGEO-[XYZ].
Set OBSGEO-B to   -26.704100 from OBSGEO-[XYZ].
Set OBSGEO-H to      121.995 from OBSGEO-[XYZ]'.
133969:source_finder:INFO Calculating background and rms data
133969:source_finder:INFO beam = 58.64'' x 45.00'' at -0.00deg
133969:source_finder:INFO seedclip=5.0
133969:source_finder:INFO floodclip=4.0
134036:pprocess:ERROR pickle data was truncated
Traceback (most recent call last):
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 1205, in start
    callable(channel, *args, **kw)
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 957, in __call__
    t = channel.receive()
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 125, in _receive
    obj = pickle.load(self.read_pipe)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/suphys/aste7152/.conda/envs/racs-transients/bin/aegean", line 336, in <module>
    found = sf.find_sources_in_image(filename, outfile=options.outfile, hdu_index=options.hdu_index,
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/source_finder.py", line 1714, in find_sources_in_image
    for srcs in queue:
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 908, in __next__
    self.store()
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 406, in store
    self.store_data(channel)
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 888, in store_data
    data = channel.receive()
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 127, in _receive
    raise obj
_pickle.UnpicklingError: pickle data was truncated
134039:pprocess:ERROR [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 1205, in start
    callable(channel, *args, **kw)
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 956, in __call__
    channel.send(self.callable(*args, **kw))
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 117, in send
    self._send(obj)
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 105, in _send
    pickle.dump(obj, self.write_pipe)
  File "/suphys/aste7152/.conda/envs/racs-transients/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by haltiamreptar** [comment]
I was able to work around this by only running in one thread. I could reliably reproduce it with different runs.

**Comment by ajstewart** [comment]
Thanks, I've now done the same. Perhaps something strange happened when I reset the screen above as now that's not a solution for me in some cases and it crashes every time. But 1 cores has done the trick.

**Comment by candersoncsiro** [comment]
I'm getting the same error. But I'm running it locally, no screen session, 8 core macbook, 32 GB mem, installed via pip3 install AegeanTools. Any developments here?

Terminal out:

"""
Source-finding for beam 22 and Stokes I

51424:aegean:INFO This is Aegean 2.1.1-(2020-01-16)
51424:aegean:INFO Found 16 cores
51424:aegean:INFO Using 16 cores
51424:aegean:INFO Finding sources.
51424:source_finder:INFO Calculating background and rms data
51424:source_finder:INFO beam = 11.76'' x  9.74'' at 90.11deg
51424:source_finder:INFO seedclip=5
51424:source_finder:INFO floodclip=4
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/aegean", line 336, in <module>
    found = sf.find_sources_in_image(filename, outfile=options.outfile, hdu_index=options.hdu_index,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/source_finder.py", line 1714, in find_sources_in_image
    for srcs in queue:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 908, in __next__
    self.store()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 406, in store
    self.store_data(channel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 888, in store_data
    data = channel.receive()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AegeanTools/pprocess.py", line 125, in _receive
    obj = pickle.load(self.read_pipe)
_pickle.UnpicklingError: pickle data was truncated

"""

**Comment by rubiculite** [comment]
I also found the same issue, and I believe I figured out why. 

When I ran Aegean, I got the following error.*
```
16064:Aegean:INFO This is Aegean 2.2.0-(2020-03-02)
16064:Aegean:INFO Found 4 cores
16064:Aegean:INFO Using 4 cores
...
16064:source_finder:INFO Begin fitting
Traceback (most recent call last):
  File "/Users/susy/opt/anaconda3/bin/Aegean", line 345, in <module>
    docov=options.docov, cube_index=options.slice)
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/source_finder.py", line 1901, in find_sources_in_image
    for srcs in queue:
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 908, in __next__
    self.store()
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 406, in store
    self.store_data(channel)
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 888, in store_data
    data = channel.receive()
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 141, in receive
    obj = self._receive()
  File "/Users/susy/opt/anaconda3/lib/python3.7/site-packages/AegeanTools/pprocess.py", line 127, in _receive
    raise obj
_pickle.UnpicklingError: pickle data was truncated
```
The first thing to note, is that this occurs for large FITS images (~ 1G), not small (~ 50M). The second thing to note, is the error message at the end, ``_pickle.UnpicklingError: pickle data was truncated``, is also mentioned in <a href="https://stackoverflow.com/questions/44637809/python-3-6-socket-pickle-data-was-truncated">stackoverflow</a>, which says it's related to trying to send partially pickled packets down a pipe. It that case it was related to TCP/IP packets, whereas in this case it's related to interprocess communication... so my hypothesis goes. In short, I believe I've traced it down to the following lines of code in ``AegeanTools/pprocess.py``; in particular, lines 404, 406 and 125.
```
...
 404             for channel in self.ready(timeout):
 405                 try:
 406                     self.store_data(channel)
 407                     self.start_waiting(channel)
 408                 except (IOError, OSError) as exc:
 409                     self.remove(channel)
 410                     warn("Removed channel %r due to exception: %s" % (channel, exc))
...
 125         obj = pickle.load(self.read_pipe)
 126         if isinstance(obj, Exception):
 127             raise obj
 128         else:
 129             return obj
...
```
Basically, you need to read the entire pipe / message, _re._, ``self.read_pipe``, before un/pickling it. This is my hypothesized fix (_cf._, <a href="https://stackoverflow.com/questions/44637809/python-3-6-socket-pickle-data-was-truncated">stackoverflow</a>).

That being said, the workaround is limiting Aegean to run using a single core for large FITS images: _i.e._, in the case of footnote (*) below, the following command works.
```
$ Aegean --autoload step_1_emu_pilot_tile_image.i.9442.cont.smooth.linmos.taylor.0.fits --table out.csv --cores 1
```
----
>*The following are notes on how to reproduce the error. The fits image, _i.e._, the EMU pilot survey image, 
>
>![EMU_Pilot_Survey_Mosaic_Michelle_Boyce_May_2020](https://user-images.githubusercontent.com/20954456/84979050-1049c400-b0f4-11ea-8838-a263c1c95906.png)
>
>can be found at this link <a href="https://data.pawsey.org.au/download/emushare/pilot_18arcsec/single_field_mosaics/image.i.9442.cont.smooth.linmos.taylor.0.fits">step_1_emu_pilot_tile_image.i.9442.cont.smooth.linmos.taylor.0.fits</a>
>
>The following are the command line steps:
>```
>$ BANE step_1_emu_pilot_tile_image.i.9442.cont.smooth.linmos.taylor.0.fits
>```
>and
>```
>$ Aegean --autoload step_1_emu_pilot_tile_image.i.9442.cont.smooth.linmos.taylor.0.fits --table >out.csv
>```
>This should reproduce the error message.

**Comment by PaulHancock** [comment]
The short story on this issue is that the `pprocess` module that I'm using is designed around `pickle` to serialise data and pass it between different processes. There is a lot of good info in this thread, so thank you all for that, and in particular to @rubiculite for figuring out exactly where the problem is. Unfortunately I have not been able to re-engineer the `pprocess` module to be able to pass large objects using either the stackoverflow method or by using `json` in place of `pickle`. I don't really understand why it's not working, but since the `pprocess` module isn't mine (and the author is unresponsive) I'm completely stuck.

I am, however, working on a version of Aegean that will do away with the `pprocess` module and use `multiprocessing` and shared memory instead. This is what was done for BANE and it works quite well. There will be a few advantages: (1) being that this stupid error wont come back, (2) being that the total memory overhead will be significantly reduced, and (3) being that it will be possible for Aegean to work with images that are larger than the available ram on the local machine/node.

**Comment by ibojicic** [comment]
Setting OPENBLAS_NUM_THREADS to the lower value from default can help:

`export OPENBLAS_NUM_THREADS=1`

pickling issue fires up from time to time, so try running the same aegean pars at least twice.
