### ISSUE TITLE
BANE's auto-output-name feature is broken

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#12]
Something is wrong with this:

BANE.py $mosaic
24601:INFO This is BANE v1.0
Traceback (most recent call last):
  File "/scratch/partner1002/code/bin/BANE.py", line 482, in <module>
    options.out_base = os.path.splitext(options.out_base)[0]
  File "/ivec/apps/gcc/4.4.7/python/2.6.9/lib/python2.6/posixpath.py", line 95, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/ivec/apps/gcc/4.4.7/python/2.6.9/lib/python2.6/genericpath.py", line 91, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by PaulHancock** [comment]
bug fixed!
