### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by jrcallingham** [PaulHancock/Aegean#140]
Hey Paul,

Running into a new issue with BANE/Aegean. This is using my old laptop (where the BANE/Aegean install is stable) and I when I try to run it on a Stokes V image I get the error below. What is odd is that it runs without any issues on the Stokes I image. I remember you said something about very large images having issues (this is large, as is it is an image at ~30 MHz) but it is weird that the Stokes I image would work but not V?

Hope you have a great Christmas break! 

Joe

In [14]: os.system('BANE --compress test_v.fits') 
    ...:                                                                            
6585:INFO This is BANE v1.8.1-(2019-12-13)
6585:INFO using grid_size (0, 0), box_size (0, 0)
6585:INFO on data shape (4060, 4060)
6585:INFO using 8 cores
6585:INFO using 8 stripes
Traceback (most recent call last):
  File "/Users/jcal/opt/anaconda3/bin/BANE", line 4, in <module>
    __import__('pkg_resources').run_script('AegeanTools==2.1.1', 'BANE')
  File "/Users/jcal/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/jcal/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/Users/jcal/opt/anaconda3/lib/python3.7/site-packages/AegeanTools-2.1.1-py3.7.egg/EGG-INFO/scripts/BANE", line 90, in <module>
    mask=options.mask, compressed=options.compress, nslice=options.stripes)
  File "/Users/jcal/opt/anaconda3/lib/python3.7/site-packages/AegeanTools-2.1.1-py3.7.egg/AegeanTools/BANE.py", line 429, in filter_image
    bkg, rms = filter_mc_sharemem(im_name, step_size=step_size, box_size=box_size, cores=cores, shape=shape, nslice=nslice, domask=mask)
  File "/Users/jcal/opt/anaconda3/lib/python3.7/site-packages/AegeanTools-2.1.1-py3.7.egg/AegeanTools/BANE.py", line 327, in filter_mc_sharemem
    width_y = int(max(img_y/nslice/step_size[1], 1) * step_size[1])
ZeroDivisionError: float division by zero

**Comment by jrcallingham** [comment]
If I force the rms and bkg values I can get Aegean to run

**Comment by PaulHancock** [comment]
The problem is likely due to:
```
6585:INFO using grid_size (0, 0), box_size (0, 0)
```
The defaults should be 5x and 20x the synthesized beam size. Possibly the input file doesn't have BMAJ or BMIN defined?

Forcing the rms/bkg to be zero will avoid the gridding step and thus avoid the issue.
