### ISSUE TITLE
Bug when using the --condon option

### ISSUE THREAD

**Issue by jameskleung** [PaulHancock/Aegean#156]
Seems to be a bug when I used Aegean while selecting the `--condon` option. The command I used was:
`aegean --condon --noise rms_img.fits --background bkg_img.fits --out output.dat img.fits`

Here, the background and rms maps were produced by BANE.
The command line output was as follows:
```
51107:aegean:INFO This is Aegean 2.2.4-(2021-05-11)
51107:aegean:INFO Using 12 cores
51107:aegean:INFO Finding sources.
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to  -107.618000 from OBSGEO-[XYZ].
Set OBSGEO-B to    34.078827 from OBSGEO-[XYZ].
Set OBSGEO-H to     2115.607 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
51107:logger:WARNING FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to  -107.618000 from OBSGEO-[XYZ].
Set OBSGEO-B to    34.078827 from OBSGEO-[XYZ].
Set OBSGEO-H to     2115.607 from OBSGEO-[XYZ]'.
51107:source_finder:INFO Loading background data from file trial_bkg.fits
51107:source_finder:INFO Loading rms data from file trial_rms.fits
51107:source_finder:INFO beam =  3.61'' x  1.74'' at 31.74deg
51107:source_finder:INFO seedclip=5
51107:source_finder:INFO floodclip=4
51107:source_finder:INFO Found 82 islands
51107:source_finder:INFO Begin fitting
51107:source_finder:INFO Fit 79 sources
Traceback (most recent call last):
  File "/.../anaconda3/envs/aegean/bin/aegean", line 384, in <module>
    fitting.condon_errors(s, theta_n=theta_n, psf=psf)
  File "/.../anaconda3/envs/aegean/lib/python3.7/site-packages/AegeanTools/fitting.py", line 873, in condon_errors
    beam = psf.get_beam(source.ra, source.dec)
AttributeError: 'WCSHelper' object has no attribute 'get_beam'
```
Seems like the `psf` object has no method `get_beam()` - a workaround that worked to fix the issue was just changing line 873 to directly access the beam attribute `beam = psf.beam`

I am using python 3.7 and Aegean version above (installed via `pip install AegeanTools`).

**Comment by PaulHancock** [comment]
This was fixed in #162
