### ISSUE TITLE
BANE fails on masking images when NAXIS>2.

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#17]
As described above:
'''
BANE.py 1117906288-I.fits
14128:INFO This is BANE v1.2-(2015-06-24)
14128:INFO using grid_size (10, 10), box_size (60, 60)
14128:INFO on data shape (3072, 3072)
14128:INFO using 64 cores
14128:INFO done
14128:INFO Wrote <open file '<fdopen>', mode 'w+b' at 0x7efc17b9b9c0>
14128:INFO running second pass to get a better rms
14128:INFO using 64 cores
Traceback (most recent call last):
  File "/usr/local/bin/BANE.py", line 4, in <module>
    __import__('pkg_resources').run_script('aegean===v1.9.6-53-g7db7f35', 'BANE.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 636, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 1557, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/aegean-v1.9.6_53_g7db7f35-py2.7.egg/EGG-INFO/scripts/BANE.py", line 789, in <module>
    mask=options.mask, compressed=options.compress)
  File "/usr/local/lib/python2.7/dist-packages/aegean-v1.9.6_53_g7db7f35-py2.7.egg/EGG-INFO/scripts/BANE.py", line 622, in filter_image
    mask_img(bkg, ref)
  File "/usr/local/lib/python2.7/dist-packages/aegean-v1.9.6_53_g7db7f35-py2.7.egg/EGG-INFO/scripts/BANE.py", line 347, in mask_img
    data[mask]=np.NaN
IndexError: too many indices for array
'''
This also seems to happen when there are no pixels to be masked.

Setting option `--nomask` avoids this problem.

**Comment by PaulHancock** [comment]
This issue is now fixed in the master branch of Aegean.
It is no longer necessary to use `--nomask` to avoid this bug.
