### ISSUE TITLE
Error running BANE

### ISSUE THREAD

**Issue by mbehiri** [PaulHancock/Aegean#200]
Hi Paul,
Whenever I run BANE I find these errors
 `4573:INFO This is BANE v1.10.0-(2022-08-17)
4573:INFO using grid_size (22, 22), box_size (132, 132)
4573:INFO on data shape (2199, 2199)
4573:INFO using 8 cores
4573:INFO using 8 stripes
Traceback (most recent call last):
  File "/Users/meriembehiri/anaconda3/lib/python3.8/site-packages/AegeanTools/BANE.py", line 370, in filter_mc_sharemem
    ibkg = SharedMemory(name=f'ibkg_{memory_id}', create=True, size=nbytes)
  File "/Users/meriembehiri/anaconda3/lib/python3.8/multiprocessing/shared_memory.py", line 100, in __init__
    self._fd = _posixshmem.shm_open(
OSError: [Errno 63] File name too long: '/ibkg_91261315-b793-49e8-b1e5-b063298426e5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meriembehiri/anaconda3/bin/bane", line 9, in <module>
    sys.exit(BANE.main(sys.argv[1:]))
  File "/Users/meriembehiri/anaconda3/lib/python3.8/site-packages/AegeanTools/CLI/BANE.py", line 87, in main
    BANE.filter_image(im_name=options.image, out_base=options.out_base,
  File "/Users/meriembehiri/anaconda3/lib/python3.8/site-packages/AegeanTools/BANE.py", line 492, in filter_image
    bkg, rms = filter_mc_sharemem(im_name,
  File "/Users/meriembehiri/anaconda3/lib/python3.8/site-packages/AegeanTools/BANE.py", line 398, in filter_mc_sharemem
    ibkg.close()
UnboundLocalError: local variable 'ibkg' referenced before assignment`
Cold you help me fixing them?
Thanks,
Meriem

**Comment by caseyjlaw** [comment]
I'm still seeing this after installing from github with:
`pip install git+https://github.com/PaulHancock/Aegean.git`

Has the fix been deployed? Judging from the PR, it is still in `dev`.

Versions:
```
aegean --version
aegean:INFO This is Aegean 2.3.0-(2022-11-29)
aegean:INFO AegeanTools 2.3.0 from /Users/claw/anaconda3arm/envs/py38/lib/python3.8/site-packages/AegeanTools/__init__.py
aegean:INFO Numpy 1.24.4 from /Users/claw/anaconda3arm/envs/py38/lib/python3.8/site-packages/numpy/__init__.py 
aegean:INFO Scipy 1.9.1 from /Users/claw/anaconda3arm/envs/py38/lib/python3.8/site-packages/scipy/__init__.py
aegean:INFO AstroPy 5.2.2 from /Users/claw/anaconda3arm/envs/py38/lib/python3.8/site-packages/astropy/__init__.py
aegean:INFO LMFit 1.3.1 from /Users/claw/anaconda3arm/envs/py38/lib/python3.8/site-packages/lmfit/__init__.py
```

**Comment by kamalpreettt12** [comment]
I am also getting this error
