### ISSUE TITLE
 No such file or directory: '/share/home/whjing/miniforge3/lib/python3.10/site-packages/AegeanTools/data/MOC.fits

### ISSUE THREAD

**Issue by whjing** [PaulHancock/Aegean#204]
Hi, when I try to use --min2fits, it didn't work. How can I fix this? 

$ MIMAS --mim2fits clean.mim clean.fits

4084788:INFO This is MIMAS v1.4.0-(2022-08-01)
Traceback (most recent call last):
  File "/share/home/whjing/miniforge3/bin/MIMAS", line 16, in <module>
    sys.exit(MIMAS.main(sys.argv[1:]))
...
  File "/share/home/whjing/miniforge3/lib/python3.10/site-packages/astropy/io/fits/file.py", line 626, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
FileNotFoundError: [Errno 2] No such file or directory: '/share/home/whjing/miniforge3/lib/python3.10/site-packages/AegeanTools/data/MOC.fits'

Thank you!

**Comment by PaulHancock** [comment]
The `MOC.fits` file should have been copied when you installed AegeanTools. How did you install Aegean tools?

**Comment by whjing** [comment]
Many thanks for your response.
I have install the AegeanTools following the guide, but it haven't been copied. 
So I copied the MOC.fits manually. It seems worked now.

**Comment by PaulHancock** [comment]
Happy to hear that you have solved the issue. I'm curious about why it came up in the first place though. When you say you installed it "following the guide" do you mean `pip install AegeanTools` or did you clone the repo and then do `python setup.py install` or some other option?

**Comment by PaulHancock** [comment]
I think this may have been fixed in d3a139e9d6844f692d4ef3b478a69c9b05c03886.

Can you check by uninstalling AegeanTools and then reinstalling with 
`pip install git+https://github.com/PaulHancock/Aegean.git@155-different-intial-guess-modes` and re-running MIMAS?

**Comment by whjing** [comment]
Sorry for the late response. Many thanks for fixing the error. I have checked, it works now. 🥰
