### ISSUE TITLE
aegean sometimes fails with lmfit==0.9.11

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#70]
The following error occurs when a source is fit but lmfit cannot produce error bars:
Trace back from a single core execution is:
```
  r = func(a, **kwargs)
Traceback (most recent call last):
  File "/home/hancock/py2.7/bin/aegean", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/data/alpha/hancock/Aegean-master/scripts/aegean", line 372, in <module>
    docov=options.docov, cube_index=options.slice)
  File "/data/alpha/hancock/Aegean-master/AegeanTools/source_finder.py", line 1516, in find_sources_in_image
    res = self._fit_island(island_data)
  File "/data/alpha/hancock/Aegean-master/AegeanTools/source_finder.py", line 1359, in _fit_island
    model.covar = result.covar
AttributeError: 'MinimizerResult' object has no attribute 'covar'
```
It turns out that the result.covar is only used in a not-yet-implemented piece of code and so line 1359 could just be deleted.

**Comment by PaulHancock** [comment]
this error doesn't occur in lmfit==0.9.10 or earlier
