### ISSUE TITLE
healpy issue on python 3

### ISSUE THREAD

**Issue by caseyjlaw** [PaulHancock/Aegean#73]
I did my first installation of aegean to play with a fits file. I'm using Python 3.
Installation seemed to go well, but running the command line task the first time produced this error:

```
/Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/healpy/pixelfunc.py:107: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn("Warning: cannot import _healpy_pixel_lib module")
Traceback (most recent call last):
  File "/Users/caseyjlaw/anaconda/envs/py36/bin/aegean", line 32, in <module>
    from AegeanTools.source_finder import scope2lat, get_aux_files
  File "/Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/AegeanTools/source_finder.py", line 36, in <module>
    from .regions import Region
  File "/Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/AegeanTools/regions.py", line 6, in <module>
    import healpy as hp
  File "/Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/healpy/__init__.py", line 81, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
ImportError: dlopen(/Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so, 2): Symbol not found: __ZN14T_Healpix_BaseIlE8SetNsideEl23Healpix_Ordering_Scheme
  Referenced from: /Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/caseyjlaw/anaconda/envs/py36/lib/python3.6/site-packages/healpy/_query_disc.cpython-36m-darwin.so
```

Probably some obscure OSX path issue, but I felt like you'd welcome the report.

**Comment by caseyjlaw** [comment]
Thanks for that. I've installed an older healpy and now aegean is only showing an pprocess error. I think I can fix that with your other installation instruction.
Thanks!
